left_ui_data = [
    {
        "title" : "Информация об организации",
        "label_post" : "Полное название организации",
        "label_fio" : "Краткое название организации",
        "value_post" : "full_org_name",
        "value_fio" : "org_name",
    },
    {
        "title" : "Местоположение организации",
        "label_post" : "Адрес",
        "label_fio" : "Населенный пункт",
        "value_post" : "address",
        "value_fio" : "location",
    },
    {
        "title" : "Лицо, утверждающее локальные документы Организации",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "main_post",
        "value_fio" : "main_fio",
    },
    {
        "title" : "Лицо, ответственное за организацию обработки персональных данных",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "ooopd_post",
        "value_fio" : "ooopd_fio",
    },
    {
        "title" : "Лицо, ответственное за обеспечение безопасности персональных данных в информационной системе персональных данных",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "ooispd_post",
        "value_fio" : "ooispd_fio",
    },
    {
        "title" : "Администратор информационной безопасности",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "admin_ib_post",
        "value_fio" : "admin_ib_fio",
    },
    {
        "title" : "Администратор информационной системы персональных данных",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "admin_ispdn_post",
        "value_fio" : "admin_ispdn_fio",
    },
    {
        "title" : "Администратор, ответственный за эксплуатацию СКЗИ",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "admin_skzi_post",
        "value_fio" : "admin_skzi_fio",
    },
]
right_ui_data = [
    {
        "title" : "Основные документы организации",
        "label_post" : "Устав",
        "label_fio" : "Лицензия",
        "value_post" : "ustav",
        "value_fio" : "license",
    },
    {
        "title" : "Председатель комиссии по обеспечению информационной безопасности и защиты персональных данных",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "main_commission_post",
        "value_fio" : "main_commission_name",
    },
    {
        "title" : "Член комиссии (1)",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "member_commission_post_1",
        "value_fio" : "member_commission_name_1",
    },
    {
        "title" : "Член комиссии (2)",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "member_commission_post_2",
        "value_fio" : "member_commission_name_2",
    },
    {
        "title" : "Член комиссии (3)",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "member_commission_post_3",
        "value_fio" : "member_commission_name_3",
    },
    {
        "title" : "Член комиссии (4)",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "member_commission_post_4",
        "value_fio" : "member_commission_name_4",
    },
    {
        "title" : "Член комиссии (5)",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "member_commission_post_5",
        "value_fio" : "member_commission_name_5",
    },
    {
        "title" : "Член комиссии (6)",
        "label_post" : "Должность",
        "label_fio" : "ФИО",
        "value_post" : "member_commission_post_6",
        "value_fio" : "member_commission_name_6",
    },
]